List quoteslist = [
  '“I gotta keep my head above water, gotta make it through.” ',
  ' “I’m not trying to be sexy. It’s just my way of expressing myself when I move around.”',
  '"Where could I go but to the Lord?"',
  '“Rock and roll music, if you like it, if you feel it, you can’t help but move to it. That’s what happens to me. I can’t help it.”',
  '“Truth is like the sun. You can shut it out for a time, but it ain’t goin’ away.”',
  '“Ambition is a dream with a V8 engine.”',
  '"Once I catch you and the kissing starts, a team of wild horses couldn’t tear us apart."',
  '"“I ain’t no saint, but I’ve tried never to do anything that would hurt my family or offend God…I figure all any kid needs is hope and the feeling he or she belongs. If I could do or say anything that would give some kid that feeling, I would believe I had contributed something to the world.” "',
  '"Whatever I will become will be what God has chosen for me.”',
  '“When I was a boy, I always saw myself as a hero in comic books and in movies. I grew up believing this dream.”',
  '“Until we meet again, may God bless you as he has blessed me.”',
  '"Wise men say only fools rush in. But I can’t help falling in love with you"',
  '"I was an only child, and Mother was always right with me all my life. I used to get very angry at her when I was growing up-it’s a natural thing."',
  '“Every time I think that I’m getting old, and gradually going to the grave, something else happens.”',
  '“Rhythm is something you either have or don’t have, but when you have it, you have it all over.”',
  ' “It’s not how much you have that makes people look up to you, it’s who you are.”',
  '“I think I have something tonight that’s not quite correct for evening wear. Blue suede shoes.”',
  '“I learned how important it is to entertain people and give them a reason to come and watch you play.”',
  '“If you let your head get too big, it’ll break your neck.”',
  '"The first time that I appeared on stage, it scared me to death. I really didn’t know what all the yelling was about. I didn’t realize that my body was moving. It’s a natural thing to me. So to the manager backstage I said, ‘What’d I do? What’d I do?’ And he said “Whatever it is, go back and do it again.”',
  '"When I first saw you with your smile so tender, my heart was captured, my soul surrendered."',
  '"Sharing money is what gives it its value."',
  '" “Values are like fingerprints. Nobody’s are the same, but you leave ’em all over everything you do.”"',
  '"The image is one thing and the human being is another. It’s very hard to live up to an image, put it that way."',
  '"Since the beginning, it was just the same. The only difference, the crowds are bigger now."',
  '"We do two shows a night for five weeks. A lotta times we’ll go upstairs and sing until daylight – gospel songs. We grew up with it…It more or less puts your mind at ease. It does mine."',
  '“After a hard day of basic training, you could eat a rattlesnake.”',
  '"In this day and time you can’t even get sick; you are strung-out! Well by God, I’ll tell you something, friend: I have never been strung-out in my life, except on music!"',
  '“It’s human nature to gripe, but I’m going ahead and doing the best I can.”',
  '"When we’re dancing it almost feels the same, I’ve got to stop myself from whispering your name."',
  '" I don’t mind being controversial. Even Jesus wasn’t loved in his day"',
  ' “When things go wrong, don’t go with them.”',
  '“A live concert to me is exciting because of all the electricity that is generated in the crowd and on stage. It’s my favorite     part of the business, live concerts.”',
  '“I knew by heart all the dialogue of James Dean’s films; I could watch Rebel Without a Cause a hundred times over.”',
  '"Do the Clam, do the Clam, grab your barefoot baby by the hand."',
  '"Happiness is knowin’ you’ve done a good job, whether it’s professional or for another person"',
  '"NUTHIN’ more fun than Rock n’ Roll!"',
  ' “When I was a child, ladies and gentlemen, I was a dreamer. I read comic books and I was the hero of the comic book. I saw movies and I was the hero in the movie. So every dream I ever dreamed has come true a hundred times…I learned very early in life that: ‘Without a song, the day would never end; without a song, a man ain’t got a friend; without a song, the road would never bend – without a song.’ So I keep singing a song. Goodnight. Thank you.” ',
  '" I wore glasses, no music, and I won – I think it was – fifth place. I got a whipping the same day. My mother whipped me for something. Destroyed my ego completely."',
  '" All I want is to know the truth, to know and experience God. I’m a searcher, that’s what I’m all about."',
  '" I don’t want to be a tiger, tigers play too rough. I don’t want to be a lion, cause lions ain’t the kind you love up."',
  '"I’ve never gotten over what they call stagefright. I go through it every show. I’m pretty concerned, I’m pretty much thinking about the show. I never get completely comfortable with it, and I don’t let the people around me get comfortable with it, in that I remind them that it’s a new crowd out there, it’s a new audience, and they haven’t seen us before. So it’s got to be like the first time we go on."',
  '“When I got outta High School I was driving a truck. I was just a poor boy from Memphis, Memphis. ”',
  '"Gospel music is the purest thing there is on this earth."',
  '"“I have no use for bodyguards, but I have very specific use for two highly trained certified public accountants.”"',
  '"“The army teaches boys to think like men.”"',
  '"Those people in New York are not gonna change me none"',
  '" I am not the King. Jesus Christ is the King. I’m just an entertainer."',
  '" Hey buddy, don’t you be no square, if you can’t find a partner use a wooden chair."',
  '" I feel my temperature rising. Help me, I’m flaming, I must be a hundred and nine"',
  '"When we kiss my heart’s on fire, burning with a strange desire. And I know that every time I kiss you, that your heart’s on fire, too."',
  ' “I’ve never gotten over what they call stagefright. I go through it every show. I’m pretty concerned, I’m pretty much thinking about the show. I never get completely comfortable with it, and I don’t let the people around me get comfortable with it, in that I remind them that it’s a new crowd out there, it’s a new audience, and they haven’t seen us before. So it’s got to be like the first time we go on.” ',
  '“I’m trying to keep a level head. You have to be careful out in the world. It’s so easy to get turned.”',
  '" It’s all a big hoax, honey. I never wrote a song in my life. I get one-third of the credit for recording it. It makes me look smarter than I am. I’ve never even had an idea for a song. Just once, maybe."',
  '“Sad thing is, you can still love someone and be wrong for them.”',
  '“The first time that I appeared on stage, it scared me to death. I really didn’t know what all the yelling was about. I didn’t realize that my body was moving. It’s a natural thing to me. So to the manager backstage I said, ‘What’d I do? What’d I do?’ And he said “Whatever it is, go back and do it again.” ',
  '"Do the Clam, do the Clam, grab your barefoot baby by the hand"',
  ' “Some people tap their feet, some people snap their fingers, and some people sway back and forth. I just sorta do ’em all together, I guess.”',
  '"Before you abuse, criticize, and accuse walk a mile in my shoes."',
  '"Animals don’t hate and we’re supposed to be better than them."',
  '"All the stars will tell the story, of our love and all its glory. Let us make this night of magic, and make it a night of love."',
  '“Do something worth remembering.”',
  '"To judge a man by his weakest link or deed is like judging the power of the ocean by one wave."',
  '"You’re just a natural beehive, filled with honey to the top. Well, I ain’t greedy baby, all I want is all you got."',
  '" The road to love is full of danger signs."',
  '"All the stars will tell the story, of our love and all its glory. Let us make this night of magic, and make it a night of love."',
  '"If you cry when you’re in love, it sure ain’t no disgrace."',
  '"A little less fight and a little more spark, close your mouth and open your heart."',
  '" If you talk in your sleep, don’t mention my name. If you walk in your sleep, forget where you came."',
  '"Make me feel at home, if you really care, scratch my back and run your pretty fingers through my hair."',
  '"Memories, pressed between the pages of my mind. Memories, sweetened through the ages just like wine."',
  '"Rock and roll is a music, and why should a music contribute to … juvenile delinquency? If people are going to be juvenile delinquents, they’re going to be delinquents if they hear … Mother Goose rhymes."',
  '"I’ve spent a life time waiting for the right time, now that you’re near, the time is here at last"',
  '" Nine and nine makes fourteen, four and four makes nine. The clock is striking thirteen, I think I’ve lost my mind."',
  '"I’ve had a pretty good lesson in human nature. It’s more important to try to surround yourself with people who can give you a little happiness, because you only pass through this life once, Jack. You don’t come back for an encore."',
  '"My philosophy of life is simple: I need someone to love, something to wait and do something."',
  '"The walls have ears, ears that hear each little sound you make every time you stamp, throw a lamp."',
  '" I’m with a crowd but oh so alone."',
  '"When you get down to the nitty gritty, isn’t it a pity that in this big city not one little bitty man will admit that he could have been a little wrong."',
  '"Love had surely made us all and hate would surely make us fall."',
  '"I’ve spent a life time waiting for the right time, now that you’re near, the time is here at last."',
  '"I go for all the belles, except the wedding kind."',
  '" She touched my hand what a chill I got, her lips are like a volcano that’s hot."',
  '"The walls have ears, ears that hear each little sound you make every time you stamp, throw a lamp."',
  '"Fame and fortune, how empty they can be."',
  '"[It’s] funny how things have a way of looking so much brighter in the daytime."',
  '"If you bring a friend into your love affair, that’s the end of your sweetheart that’s the end of your friend, that’s when your heartache begins."',
  '"Envy someone an’ it pulls you down. Admire them and it builds you up. Which makes more sense?"',
  '"I’m not trying to be sexy. It’s just my way of expressing myself when I move around."',
  '"I like Brando’s acting … and James Dean … and Richard Widmark. Quite a few of ’em I like."',
  '"I believe in the Bible. I believe that all good things come from God. I don’t believe I’d sing the way I do if God hadn’t wanted me to.’"',
  '"Teenagers are my life and my triumph. I’d be nowhere without them."',
  '"Love is a thing you never can share."',
  '"When I was a child, ladies and gentlemen, I was a dreamer. I read comic books and I was the hero of the comic book. I saw movies and I was the hero in the movie. So every dream I ever dreamed has come true a hundred times…I learned very early in life that: ‘Without a song, the day would never end; without a song, a man ain’t got a friend; without a song, the road would never bend – without a song.’ So I keep singing a song. Goodnight. Thank you."',
  '" The first car I bought was the most beautiful car I’ve ever seen. It was secondhand, but I parked it outside of my hotel the day I got it. I sat up all night, just lookin’ at it."',
  '"I like pork chops and country ham, creamed potatoes, stuff like that. Redeye gravy. It comes from ham, bacon, stuff like that. It’s the grease that you fry it in. I eat a lot of Jell-O. Fruit Jell-O."',
  '"Blacko-oxy-tonic phosphate, it’s the latest scoop. But that’s alright girls, you can call it goop."',
  '"Money honey, if you want to get along with me."',
  '"What’s the good of reaching 90, if you waste 89?"',
  '"Viva Las Vegas with your neon flashin’ and your one arm bandits crashin’ all those hopes down the drain. Viva Las Vegas turnin’ day into nighttime, turnin night into daytime. If you see it once, you’ll never be the same again."',
  '" I learned very early in life that: ‘Without a song, the day would never end; without a friend, a man ain’t got a friend; without a song, the road would never bend-without a song.’ So I keep singing a song."',
  '"I’ll never feel comfortable taking a strong drink, and I’ll never feel easy smoking a cigarette. I just don’t think those things are right for me."',
  '" Computers may out think us one day, but as long as people got feelings we’ll be better than they are."',
  '"That’s why I hate to get started in these jam sessions. I’m always the last one to leave."',
  '"A lot of people seem to think I started this business. But rock ‘n’ roll was here a long time before I came along. Nobody can sing that kind of music like colored people. Let’s face it: I can’t sing like Fats Domino can. I know that."',
  '"I get tired of playing a guy who gets into a fight, then starts singing to the guy he’s just beat up."',
  '"My fans want my shirt. They can have my shirt. They put it on my back."',
  '"Take care of the fans and they will sure as hell take care of you."',
  '" I don’t like to be called Elvis the Pelvis. It’s one of the most childish expressions I’ve ever heard coming from an adult. But if they wanna call me that, there’s nothin’ I can do about it, so I just have to accept it."',
  '"It’s not just self defense, it’s about…self control, body discipline, and mind discipline…and breath techniques. It involves yoga. It involves meditation. It’s an art, not a sport."',
  '"Ma’am, I’m not tryin’ to be sexy. Ah didn’t have any clear idea of trying to sell sex. It’s just my way of expressin’ how I feel when I move around. It’s all leg movement. I don’t do nothin’ with my body."',
];
